Class {
	#name : 'AClassToInstrumentCopy',
	#superclass : 'Object',
	#category : 'InstrumentationProfilers-Tests-SourceCodeModificator',
	#package : 'InstrumentationProfilers-Tests',
	#tag : 'SourceCodeModificator'
}

{ #category : 'accessing' }
AClassToInstrumentCopy >> bar [

	SingletonClasToTest current increment
]

{ #category : 'accessing' }
AClassToInstrumentCopy >> foo [

	SingletonClasToTest current increment
]

{ #category : 'accessing' }
AClassToInstrumentCopy >> poo [

	SingletonClasToTest current increment
]
